[project]
name = "benchmark"
version = "0.1.0"
description = "LLM Performance Benchmark Tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.24.0",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
]
